//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profile.DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddLinkEntity : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.Links",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Url = c.String(),
                        Description = c.String(),
                        TraineeProfileId = c.Int(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.TraineeProfiles", t => t.TraineeProfileId)
                .Index(t => t.TraineeProfileId);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Links", "TraineeProfileId", "dbo.TraineeProfiles");
            DropIndex("dbo.Links", new[] { "TraineeProfileId" });
            DropTable("dbo.Links");
        }
    }
}
