//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profile.DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class UpdateProjectEntity : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Projects", "IsInArchive", c => c.Boolean(nullable: false));
            AddColumn("dbo.Projects", "Status", c => c.Int(nullable: false));
        }
        
        public override void Down()
        {
            DropColumn("dbo.Projects", "Status");
            DropColumn("dbo.Projects", "IsInArchive");
        }
    }
}
