//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profile.DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class SetNullableForeignKeyToMentorForTrainee : DbMigration
    {
        public override void Up()
        {
            DropIndex("dbo.Trainees", new[] { "MentorId" });
            AlterColumn("dbo.Trainees", "MentorId", c => c.Int());
            CreateIndex("dbo.Trainees", "MentorId");
        }
        
        public override void Down()
        {
            DropIndex("dbo.Trainees", new[] { "MentorId" });
            AlterColumn("dbo.Trainees", "MentorId", c => c.Int(nullable: false));
            CreateIndex("dbo.Trainees", "MentorId");
        }
    }
}
