//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profile.DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddMentorEntity : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.Mentors",
                c => new
                    {
                        Id = c.Int(nullable: false),
                        FullName = c.String(),
                        ContactEmail = c.String(),
                        Phone = c.String(),
                        Skype = c.String(),
                        LinkedIn = c.String(),
                        SpecializationId = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Users", t => t.Id)
                .ForeignKey("dbo.Specializations", t => t.SpecializationId, cascadeDelete: true)
                .Index(t => t.Id)
                .Index(t => t.SpecializationId);
            
            AddColumn("dbo.Trainees", "MentorId", c => c.Int(nullable: false));
            CreateIndex("dbo.Trainees", "MentorId");
            AddForeignKey("dbo.Trainees", "MentorId", "dbo.Mentors", "Id");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Trainees", "MentorId", "dbo.Mentors");
            DropForeignKey("dbo.Mentors", "SpecializationId", "dbo.Specializations");
            DropForeignKey("dbo.Mentors", "Id", "dbo.Users");
            DropIndex("dbo.Trainees", new[] { "MentorId" });
            DropIndex("dbo.Mentors", new[] { "SpecializationId" });
            DropIndex("dbo.Mentors", new[] { "Id" });
            DropColumn("dbo.Trainees", "MentorId");
            DropTable("dbo.Mentors");
        }
    }
}
