//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profile.DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class CorrectPropertyName : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Groups", "TeamworkDescription", c => c.String());
            DropColumn("dbo.Groups", "TeamworkDesciption");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Groups", "TeamworkDesciption", c => c.String());
            DropColumn("dbo.Groups", "TeamworkDescription");
        }
    }
}
