//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profile.DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class RenameEducationToUniversity : DbMigration
    {
        public override void Up()
        {
            RenameTable(name: "dbo.Educations", newName: "Universities");
        }
        
        public override void Down()
        {
            RenameTable(name: "dbo.Universities", newName: "Educations");
        }
    }
}
