//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profile.DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class EditGroupToScrumMasterRelation : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Groups", "ScrumMasterId", c => c.Int());
            CreateIndex("dbo.Groups", "ScrumMasterId");
            AddForeignKey("dbo.Groups", "ScrumMasterId", "dbo.ScrumMasters", "Id");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Groups", "ScrumMasterId", "dbo.ScrumMasters");
            DropIndex("dbo.Groups", new[] { "ScrumMasterId" });
            DropColumn("dbo.Groups", "ScrumMasterId");
        }
    }
}
