//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profile.DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddScrumMasterAndReviewEntities : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.TraineeProfileMainSkills", "MainSkill_Id", "dbo.MainSkills");
            DropPrimaryKey("dbo.MainSkills");
            DropPrimaryKey("dbo.SoftSkills");
            CreateTable(
                "dbo.Skills",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Name = c.String(),
                        SkillType = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.Reviews",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        ReviewType = c.Int(nullable: false),
                        ReviewerId = c.Int(nullable: false),
                        ReviewedTraineeId = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Trainees", t => t.ReviewedTraineeId)
                .ForeignKey("dbo.Users", t => t.ReviewerId, cascadeDelete: true)
                .Index(t => t.ReviewerId)
                .Index(t => t.ReviewedTraineeId);
            
            CreateTable(
                "dbo.Grades",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Comment = c.String(),
                        Mark = c.Int(),
                        ReviewId = c.Int(),
                        SkillId = c.Int(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Reviews", t => t.ReviewId)
                .ForeignKey("dbo.Skills", t => t.SkillId)
                .Index(t => t.ReviewId)
                .Index(t => t.SkillId);
            
            CreateTable(
                "dbo.Abilities",
                c => new
                    {
                        Id = c.Int(nullable: false),
                        Description = c.String(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Skills", t => t.Id)
                .Index(t => t.Id);
            
            CreateTable(
                "dbo.ScrumMasters",
                c => new
                    {
                        Id = c.Int(nullable: false),
                        GroupId = c.Int(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Users", t => t.Id)
                .ForeignKey("dbo.Groups", t => t.GroupId)
                .Index(t => t.Id)
                .Index(t => t.GroupId);
            
            AlterColumn("dbo.MainSkills", "Id", c => c.Int(nullable: false));
            AlterColumn("dbo.SoftSkills", "Id", c => c.Int(nullable: false));
            AddPrimaryKey("dbo.MainSkills", "Id");
            AddPrimaryKey("dbo.SoftSkills", "Id");
            CreateIndex("dbo.MainSkills", "Id");
            CreateIndex("dbo.SoftSkills", "Id");
            AddForeignKey("dbo.MainSkills", "Id", "dbo.Skills", "Id");
            AddForeignKey("dbo.SoftSkills", "Id", "dbo.Skills", "Id");
            AddForeignKey("dbo.TraineeProfileMainSkills", "MainSkill_Id", "dbo.MainSkills", "Id", cascadeDelete: true);
            DropColumn("dbo.MainSkills", "Name");
            DropColumn("dbo.SoftSkills", "Name");
        }
        
        public override void Down()
        {
            AddColumn("dbo.SoftSkills", "Name", c => c.String());
            AddColumn("dbo.MainSkills", "Name", c => c.String());
            DropForeignKey("dbo.TraineeProfileMainSkills", "MainSkill_Id", "dbo.MainSkills");
            DropForeignKey("dbo.SoftSkills", "Id", "dbo.Skills");
            DropForeignKey("dbo.ScrumMasters", "GroupId", "dbo.Groups");
            DropForeignKey("dbo.ScrumMasters", "Id", "dbo.Users");
            DropForeignKey("dbo.MainSkills", "Id", "dbo.Skills");
            DropForeignKey("dbo.Abilities", "Id", "dbo.Skills");
            DropForeignKey("dbo.Reviews", "ReviewerId", "dbo.Users");
            DropForeignKey("dbo.Reviews", "ReviewedTraineeId", "dbo.Trainees");
            DropForeignKey("dbo.Grades", "SkillId", "dbo.Skills");
            DropForeignKey("dbo.Grades", "ReviewId", "dbo.Reviews");
            DropIndex("dbo.SoftSkills", new[] { "Id" });
            DropIndex("dbo.ScrumMasters", new[] { "GroupId" });
            DropIndex("dbo.ScrumMasters", new[] { "Id" });
            DropIndex("dbo.MainSkills", new[] { "Id" });
            DropIndex("dbo.Abilities", new[] { "Id" });
            DropIndex("dbo.Grades", new[] { "SkillId" });
            DropIndex("dbo.Grades", new[] { "ReviewId" });
            DropIndex("dbo.Reviews", new[] { "ReviewedTraineeId" });
            DropIndex("dbo.Reviews", new[] { "ReviewerId" });
            DropPrimaryKey("dbo.SoftSkills");
            DropPrimaryKey("dbo.MainSkills");
            AlterColumn("dbo.SoftSkills", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.MainSkills", "Id", c => c.Int(nullable: false, identity: true));
            DropTable("dbo.ScrumMasters");
            DropTable("dbo.Abilities");
            DropTable("dbo.Grades");
            DropTable("dbo.Reviews");
            DropTable("dbo.Skills");
            AddPrimaryKey("dbo.SoftSkills", "Id");
            AddPrimaryKey("dbo.MainSkills", "Id");
            AddForeignKey("dbo.TraineeProfileMainSkills", "MainSkill_Id", "dbo.MainSkills", "Id", cascadeDelete: true);
        }
    }
}
