//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profile.DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class RelatedToTrainees : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.Groups",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Number = c.String(),
                        ReleaseId = c.Int(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Releases", t => t.ReleaseId)
                .Index(t => t.ReleaseId);
            
            CreateTable(
                "dbo.Releases",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Name = c.String(),
                        StartDate = c.DateTime(nullable: false),
                        ReleaseDate = c.DateTime(nullable: false),
                        ProjectId = c.Int(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Projects", t => t.ProjectId)
                .Index(t => t.ProjectId);
            
            CreateTable(
                "dbo.Projects",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Name = c.String(),
                        FullDescription = c.String(),
                        ShortDescription = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.Specializations",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Name = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.Trainees",
                c => new
                    {
                        Id = c.Int(nullable: false),
                        FullName = c.String(),
                        IsAllowed = c.Boolean(nullable: false),
                        GroupId = c.Int(),
                        SpecializationId = c.Int(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Users", t => t.Id)
                .ForeignKey("dbo.Groups", t => t.GroupId)
                .ForeignKey("dbo.Specializations", t => t.SpecializationId)
                .Index(t => t.Id)
                .Index(t => t.GroupId)
                .Index(t => t.SpecializationId);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Trainees", "SpecializationId", "dbo.Specializations");
            DropForeignKey("dbo.Trainees", "GroupId", "dbo.Groups");
            DropForeignKey("dbo.Trainees", "Id", "dbo.Users");
            DropForeignKey("dbo.Releases", "ProjectId", "dbo.Projects");
            DropForeignKey("dbo.Groups", "ReleaseId", "dbo.Releases");
            DropIndex("dbo.Trainees", new[] { "SpecializationId" });
            DropIndex("dbo.Trainees", new[] { "GroupId" });
            DropIndex("dbo.Trainees", new[] { "Id" });
            DropIndex("dbo.Releases", new[] { "ProjectId" });
            DropIndex("dbo.Groups", new[] { "ReleaseId" });
            DropTable("dbo.Trainees");
            DropTable("dbo.Specializations");
            DropTable("dbo.Projects");
            DropTable("dbo.Releases");
            DropTable("dbo.Groups");
        }
    }
}
