//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profile.DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class RemoveReleaseAddDatesToProjectsAndTeams : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Groups", "ReleaseId", "dbo.Releases");
            DropForeignKey("dbo.Releases", "ProjectId", "dbo.Projects");
            DropIndex("dbo.Groups", new[] { "ReleaseId" });
            DropIndex("dbo.Releases", new[] { "ProjectId" });
            AddColumn("dbo.Groups", "StartDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Groups", "FinishDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Groups", "ProjectId", c => c.Int());
            AddColumn("dbo.Projects", "StartDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Projects", "FinishDate", c => c.DateTime(nullable: false));
            CreateIndex("dbo.Groups", "ProjectId");
            AddForeignKey("dbo.Groups", "ProjectId", "dbo.Projects", "Id");
            DropColumn("dbo.Groups", "ReleaseId");
            DropTable("dbo.Releases");
        }
        
        public override void Down()
        {
            CreateTable(
                "dbo.Releases",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Name = c.String(),
                        StartDate = c.DateTime(nullable: false),
                        ReleaseDate = c.DateTime(nullable: false),
                        ProjectId = c.Int(),
                    })
                .PrimaryKey(t => t.Id);
            
            AddColumn("dbo.Groups", "ReleaseId", c => c.Int());
            DropForeignKey("dbo.Groups", "ProjectId", "dbo.Projects");
            DropIndex("dbo.Groups", new[] { "ProjectId" });
            DropColumn("dbo.Projects", "FinishDate");
            DropColumn("dbo.Projects", "StartDate");
            DropColumn("dbo.Groups", "ProjectId");
            DropColumn("dbo.Groups", "FinishDate");
            DropColumn("dbo.Groups", "StartDate");
            CreateIndex("dbo.Releases", "ProjectId");
            CreateIndex("dbo.Groups", "ReleaseId");
            AddForeignKey("dbo.Releases", "ProjectId", "dbo.Projects", "Id");
            AddForeignKey("dbo.Groups", "ReleaseId", "dbo.Releases", "Id");
        }
    }
}
