//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profile.DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddLinkFromTraineeProfileAndMainSkill : DbMigration
    {
        public override void Up()
        {
            RenameTable(name: "dbo.Skills", newName: "MainSkills");
            CreateTable(
                "dbo.MainSkillTraineeProfiles",
                c => new
                    {
                        MainSkill_Id = c.Int(nullable: false),
                        TraineeProfile_Id = c.Int(nullable: false),
                    })
                .PrimaryKey(t => new { t.MainSkill_Id, t.TraineeProfile_Id })
                .ForeignKey("dbo.MainSkills", t => t.MainSkill_Id, cascadeDelete: true)
                .ForeignKey("dbo.TraineeProfiles", t => t.TraineeProfile_Id, cascadeDelete: true)
                .Index(t => t.MainSkill_Id)
                .Index(t => t.TraineeProfile_Id);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.MainSkillTraineeProfiles", "TraineeProfile_Id", "dbo.TraineeProfiles");
            DropForeignKey("dbo.MainSkillTraineeProfiles", "MainSkill_Id", "dbo.MainSkills");
            DropIndex("dbo.MainSkillTraineeProfiles", new[] { "TraineeProfile_Id" });
            DropIndex("dbo.MainSkillTraineeProfiles", new[] { "MainSkill_Id" });
            DropTable("dbo.MainSkillTraineeProfiles");
            RenameTable(name: "dbo.MainSkills", newName: "Skills");
        }
    }
}
