//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profile.DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class MoveFullNamePropertyToUserEntity : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Users", "FullName", c => c.String());
            DropColumn("dbo.Mentors", "FullName");
            DropColumn("dbo.Trainees", "FullName");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Trainees", "FullName", c => c.String());
            AddColumn("dbo.Mentors", "FullName", c => c.String());
            DropColumn("dbo.Users", "FullName");
        }
    }
}
